#ifndef GEOSTREAMLIB_GLOBAL_H
#define GEOSTREAMLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GEOSTREAMLIB_LIBRARY)
#  define GEOSTREAMLIBLIBRARY_EXPORT Q_DECL_EXPORT
#else
#  define GEOSTREAMLIBLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // GEOSTREAMLIB_GLOBAL_H
